pipeline:
    name: ci-test
    identifier: citest
    allowStageExecutions: false
    projectIdentifier: tf_provider
    orgIdentifier: Micahs_Projects
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: micahlmartinterraformproviderharness
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: go mod download
                                identifier: go_mod_download
                                spec:
                                    connectorRef: account.harnessImage
                                    image: golang:<+pipeline.variables.GO_VERSION>
                                    command: |
                                        # go mod download
                                        #go env | sort
                                        #echo "----->"
                                        #env | sort

                                        go mod download

                                        ls -la $(go env GOCACHE)
                                        echo "----->"
                                        ls -la $(go env GOMODCACHE)
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: account.harnessImage
                                    image: golang:<+pipeline.variables.GO_VERSION>
                                    command: |-
                                        ls -la $(go env GOCACHE)
                                        echo "---->"
                                        ls -la $(go env GOMODCACHE)
                  sharedPaths:
                      - <+pipeline.variables.GOCACHE>
                      - <+pipeline.variables.GOMODCACHE>
    variables:
        - name: GO_VERSION
          type: String
          default: 1.17.6
          value: <+input>
        - name: GOCACHE
          type: String
          value: /root/.cache/go-build
        - name: GOMODCACHE
          type: String
          value: /go/pkg/mod
