pipeline:
    name: ci-test
    identifier: citest
    allowStageExecutions: false
    projectIdentifier: tf_provider
    orgIdentifier: Micahs_Projects
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: micahlmartinterraformproviderharness
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheGCS
                                name: restore go cache
                                identifier: restore_cache
                                spec:
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    key: go-mod-cahe-{{ checksum "go.mod" }}
                                    archiveFormat: Tar
                          - step:
                                type: Run
                                name: go mod download
                                identifier: go_mod_download
                                spec:
                                    connectorRef: account.harnessImage
                                    image: golang:<+pipeline.variables.GO_VERSION>
                                    command: |
                                        go mod download
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                          - step:
                                type: SaveCacheGCS
                                name: save cache
                                identifier: save_cache
                                spec:
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    key: go-mod-cache-{{ checksum "go.mod" }}
                                    sourcePaths:
                                        - <+pipeline.variables.GOMODCACHE>
                                    archiveFormat: Tar
                          - step:
                                type: RestoreCacheGCS
                                spec:
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    key: build-cache-{{ checksum "go.mod" }}-{{ checksum "internal/**" }}
                                    archiveFormat: Gzip
                                    resources:
                                        limits:
                                            memory: 1Gi
                                            cpu: "1"
                                name: restore build cache
                                identifier: restore_build_cache
                          - step:
                                type: Run
                                name: go build
                                identifier: go_build
                                spec:
                                    connectorRef: account.harnessImage
                                    image: golang:<+pipeline.variables.GO_VERSION>
                                    command: go build -v
                                    resources:
                                        limits:
                                            memory: 4Gi
                                            cpu: "1"
                          - step:
                                type: SaveCacheGCS
                                name: save cache
                                identifier: save_build_cache
                                spec:
                                    connectorRef: org.gcp
                                    bucket: harness-micah-test
                                    key: build-cache-{{ checksum "go.mod" }}-{{ checksum "internal/**" }}
                                    sourcePaths:
                                        - <+pipeline.variables.GOCACHE>
                                    archiveFormat: Tar
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: account.harnessImage
                                    image: golang:<+pipeline.variables.GO_VERSION>
                                    command: |-
                                        ls -la $(go env GOCACHE)
                                        echo "---->"
                                        ls -la $(go env GOMODCACHE)
                  sharedPaths:
                      - <+pipeline.variables.GOCACHE>
                      - <+pipeline.variables.GOMODCACHE>
              variables: []
    variables:
        - name: GO_VERSION
          type: String
          default: 1.17.6
          value: <+input>
        - name: GOCACHE
          type: String
          value: /root/.cache/go-build
        - name: GOMODCACHE
          type: String
          value: /go/pkg/mod
        - name: TERRAFORM_VERSION
          type: String
          default: 1.0.6
          value: <+input>
