pipeline:
    name: generatechangelogtest
    identifier: generatechangelogtest
    allowStageExecutions: false
    projectIdentifier: tf_provider
    orgIdentifier: Micahs_Projects
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: micahlmartinterraformproviderharness
                build: <+input>
    stages:
        - stage:
              name: generate-changelog
              identifier: generatechangelog
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: git fetch
                                identifier: gitfetch
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: |
                                        git fetch --unshallow
                                when:
                                    stageStatus: Success
                                    condition: "false"
                                failureStrategies: []
                          - step:
                                type: Run
                                name: generate changelog
                                identifier: generate
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: |-
                                        $(cd tools && go install github.com/hashicorp/go-changelog/cmd/changelog-build)

                                        ./scripts/generate-changelog.sh

                                        if [[ `git status --porcelain` ]]; then
                                            #if ${{github.event_name == 'workflow_dispatch'}}; then
                                            #    MSG="Update CHANGELOG.md (Manual Trigger)"
                                            #else
                                                MSG="Update CHANGELOG.md for #<+trigger.payload.pull_request.number>"
                                            #fi
                                            git config --local user.email changelogbot@harness.io
                                            git config --local user.name changelogbot
                                            git add CHANGELOG.md
                                            git commit -m "$MSG" 
                                            git push
                                        fi
              variables: []
