pipeline:
    name: generatechangelogtest
    identifier: generatechangelogtest
    allowStageExecutions: false
    projectIdentifier: tf_provider
    orgIdentifier: Micahs_Projects
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: micahlmartinterraformproviderharness
                build: <+input>
    stages:
        - stage:
              name: generate-changelog
              identifier: generatechangelog
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.micahsprojects
                          namespace: micahs-projects
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: git fetch
                                identifier: gitfetch
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: |
                                        git fetch --unshallow
                          - step:
                                type: Run
                                name: install tools
                                identifier: install
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: |
                                        cd tools && go install github.com/hashicorp/go-changelog/cmd/changelog-build
                          - step:
                                type: Run
                                name: generate changelog
                                identifier: generate
                                spec:
                                    connectorRef: org.gcp
                                    image: us.gcr.io/sales-209522/micah/go-build-tools:1.16-stretch-8
                                    command: |
                                        ./scripts/generate-changelog.sh
